<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Rajats-MacBook-Air.local" failures="4" tests="16" name="HealthCheckTest" time="5.275" errors="0" timestamp="2025-08-05T23:57:14 IST">
  <testcase classname="com.pacakge.rest_assured_framework.HealthCheckAPI" name="shouldReturnStatus200" time="1.412"/>
  <testcase classname="com.pacakge.rest_assured_framework.HealthCheckAPI" name="shouldContainStatusKey" time="0.322"/>
  <testcase classname="com.pacakge.rest_assured_framework.HealthCheckAPI" name="shouldReturnStatusValueUp" time="0.53"/>
  <testcase classname="com.pacakge.rest_assured_framework.HealthCheckAPI" name="shouldNotAllowPostMethod" time="0.049"/>
  <testcase classname="com.pacakge.rest_assured_framework.HealthCheckAPI" name="shouldReturn404ForInvalidEndpoint" time="0.017"/>
  <testcase classname="com.pacakge.rest_assured_framework.SignUpAPI" name="testSignupSuccess" time="0.426"/>
  <testcase classname="com.pacakge.rest_assured_framework.SignUpAPI" name="testSignupWithComplexPassword" time="0.323"/>
  <testcase classname="com.pacakge.rest_assured_framework.SignUpAPI" name="testSignupWithExistingEmail" time="0.342"/>
  <testcase classname="com.pacakge.rest_assured_framework.SignUpAPI" name="testSignupWithEmptyEmail" time="0.042"/>
  <testcase classname="com.pacakge.rest_assured_framework.SignUpAPI" name="testSignupWithEmptyPassword" time="0.317">
    <failure type="java.lang.AssertionError" message="Unexpected status code. Response: {
    &amp;quot;message&amp;quot;: &amp;quot;User created successfully&amp;quot;
} expected [400] but found [200]">
      <![CDATA[java.lang.AssertionError: Unexpected status code. Response: {
    "message": "User created successfully"
} expected [400] but found [200]
at com.pacakge.rest_assured_framework.SignUpAPI.assertResponse(SignUpAPI.java:39)
at com.pacakge.rest_assured_framework.SignUpAPI.testSignupWithEmptyPassword(SignUpAPI.java:112)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testSignupWithEmptyPassword -->
  <testcase classname="com.pacakge.rest_assured_framework.SignUpAPI" name="testSignupWithInvalidEmailFormat" time="0.045"/>
  <testcase classname="com.pacakge.rest_assured_framework.SignUpAPI" name="testSignupWithShortPassword" time="0.272">
    <failure type="java.lang.AssertionError" message="Unexpected status code. Response: {
    &amp;quot;message&amp;quot;: &amp;quot;User created successfully&amp;quot;
} expected [400] but found [200]">
      <![CDATA[java.lang.AssertionError: Unexpected status code. Response: {
    "message": "User created successfully"
} expected [400] but found [200]
at com.pacakge.rest_assured_framework.SignUpAPI.assertResponse(SignUpAPI.java:39)
at com.pacakge.rest_assured_framework.SignUpAPI.testSignupWithShortPassword(SignUpAPI.java:132)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testSignupWithShortPassword -->
  <testcase classname="com.pacakge.rest_assured_framework.SignUpAPI" name="testSignupWithNullValues" time="0.058">
    <failure type="java.lang.AssertionError" message="Unexpected status code. Response: Internal Server Error expected [400] but found [500]">
      <![CDATA[java.lang.AssertionError: Unexpected status code. Response: Internal Server Error expected [400] but found [500]
at com.pacakge.rest_assured_framework.SignUpAPI.assertResponse(SignUpAPI.java:39)
at com.pacakge.rest_assured_framework.SignUpAPI.testSignupWithNullValues(SignUpAPI.java:139)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testSignupWithNullValues -->
  <testcase classname="com.pacakge.rest_assured_framework.SignUpAPI" name="testSignupWithVeryLongEmail" time="0.053"/>
  <testcase classname="com.pacakge.rest_assured_framework.SignUpAPI" name="testSignupWithVeryLongPassword" time="0.304">
    <failure type="java.lang.AssertionError" message="Unexpected status code. Response: {
    &amp;quot;message&amp;quot;: &amp;quot;User created successfully&amp;quot;
} expected [400] but found [200]">
      <![CDATA[java.lang.AssertionError: Unexpected status code. Response: {
    "message": "User created successfully"
} expected [400] but found [200]
at com.pacakge.rest_assured_framework.SignUpAPI.assertResponse(SignUpAPI.java:39)
at com.pacakge.rest_assured_framework.SignUpAPI.testSignupWithVeryLongPassword(SignUpAPI.java:161)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testSignupWithVeryLongPassword -->
  <testcase classname="com.pacakge.rest_assured_framework.SignUpAPI" name="testSignupWithEmailContainingSpaces" time="0.063"/>
</testsuite> <!-- HealthCheckTest -->
